const Rule = @import("../rules.zig").Rule;
const Category = @import("../rules.zig").Category;
const Risk = @import("../rules.zig").Risk;

pub const rules = [_]Rule{
    .{
        .name = "node_modules",
        .description = "Node.js dependencies (reinstall with npm/yarn/pnpm install)",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = "node_modules" },
    },
    .{
        .name = ".next",
        .description = "Next.js build cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".next" },
    },
    .{
        .name = ".nuxt",
        .description = "Nuxt.js build cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".nuxt" },
    },
    .{
        .name = ".parcel-cache",
        .description = "Parcel bundler cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".parcel-cache" },
    },
    .{
        .name = ".turbo",
        .description = "Turborepo cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".turbo" },
    },
    .{
        .name = ".angular",
        .description = "Angular build cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".angular" },
    },
    .{
        .name = ".svelte-kit",
        .description = "SvelteKit build output",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".svelte-kit" },
    },
    .{
        .name = ".expo",
        .description = "Expo (React Native) cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".expo" },
    },
    .{
        .name = "dist",
        .description = "Build output directory",
        .category = .dev,
        .risk = .moderate,
        .detection = .{ .marker_file = .{ .marker = "package.json", .targets = &.{"dist"} } },
    },
    .{
        .name = "cargo-target",
        .description = "Rust build artifacts (rebuild with cargo build)",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .marker_file = .{ .marker = "Cargo.toml", .targets = &.{"target"} } },
    },
    .{
        .name = ".zig-cache",
        .description = "Zig build cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".zig-cache" },
    },
    .{
        .name = "zig-out",
        .description = "Zig build output",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = "zig-out" },
    },
    .{
        .name = "__pycache__",
        .description = "Python bytecode cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = "__pycache__" },
    },
    .{
        .name = ".venv",
        .description = "Python virtual environment",
        .category = .dev,
        .risk = .moderate,
        .detection = .{ .dir_name = ".venv" },
    },
    .{
        .name = "venv",
        .description = "Python virtual environment",
        .category = .dev,
        .risk = .moderate,
        .detection = .{ .dir_name = "venv" },
    },
    .{
        .name = ".tox",
        .description = "Tox test environments",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".tox" },
    },
    .{
        .name = ".pytest_cache",
        .description = "Pytest cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".pytest_cache" },
    },
    .{
        .name = ".mypy_cache",
        .description = "Mypy type checker cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".mypy_cache" },
    },
    .{
        .name = ".ruff_cache",
        .description = "Ruff linter cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".ruff_cache" },
    },
    .{
        .name = ".gradle",
        .description = "Gradle build cache",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = ".gradle" },
    },
    .{
        .name = "gradle-build",
        .description = "Gradle build output",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .marker_file = .{ .marker = "build.gradle", .targets = &.{"build"} } },
    },
    .{
        .name = "go-vendor",
        .description = "Go vendored dependencies",
        .category = .dev,
        .risk = .moderate,
        .detection = .{ .marker_file = .{ .marker = "go.mod", .targets = &.{"vendor"} } },
    },
    .{
        .name = "cmake-build",
        .description = "CMake build directory",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = "CMakeFiles" },
    },
    .{
        .name = "coverage",
        .description = "Code coverage reports",
        .category = .dev,
        .risk = .safe,
        .detection = .{ .dir_name = "coverage" },
    },
};
