const Rule = @import("../rules.zig").Rule;

pub const rules = [_]Rule{
    .{
        .name = "npm-cache",
        .description = "npm package cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.npm/_cacache" },
    },
    .{
        .name = "yarn-cache",
        .description = "Yarn package cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.cache/yarn" },
    },
    .{
        .name = "pnpm-store",
        .description = "pnpm content-addressable store",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.local/share/pnpm/store" },
    },
    .{
        .name = "pip-cache",
        .description = "pip download cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.cache/pip" },
    },
    .{
        .name = "cargo-registry",
        .description = "Cargo crate registry cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.cargo/registry" },
    },
    .{
        .name = "cargo-git",
        .description = "Cargo git checkout cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.cargo/git" },
    },
    .{
        .name = "go-build-cache",
        .description = "Go build cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.cache/go-build" },
    },
    .{
        .name = "go-mod-cache",
        .description = "Go module cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/go/pkg/mod" },
    },
    .{
        .name = "gem-cache",
        .description = "RubyGems cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.local/share/gem" },
    },
    .{
        .name = "nix-cache",
        .description = "Nix user cache",
        .category = .package,
        .risk = .moderate,
        .detection = .{ .path_prefix = "~/.cache/nix" },
    },
    .{
        .name = "linuxbrew-cache",
        .description = "Homebrew (Linux) cache",
        .category = .package,
        .risk = .safe,
        .detection = .{ .path_prefix = "~/.cache/Homebrew" },
    },
    .{
        .name = "maven-cache",
        .description = "Maven local repository",
        .category = .package,
        .risk = .moderate,
        .detection = .{ .path_prefix = "~/.m2/repository" },
    },
    .{
        .name = "gradle-caches",
        .description = "Gradle global caches",
        .category = .package,
        .risk = .moderate,
        .detection = .{ .path_prefix = "~/.gradle/caches" },
    },
};
